//SSBM Regions Go Here!
/*********************************************************************************************************************************************************************************************
//*****SSSSSS**********SSSSSS*******BBBBBBBBBBB*****BMMMMM******MMMMMM**********RRRRRRRRRRR******EEEEEEEEEEEEE********GGGGGGG******GIII********OOOOOO********NNNN******NNNN******SSSSSSS******
//***SSSSSSSSSS******SSSSSSSSSS*****BBBBBBBBBBBBB***BMMMMMM*****MMMMMM**********RRRRRRRRRRRRR****EEEEEEEEEEEEE*****GGGGGGGGGGGG****GIII******OOOOOOOOOO******NNNNN*****NNNN****SSSSSSSSSSS****
//**SSSSSSSSSSSS****SSSSSSSSSSSS****BBBBBBBBBBBBB***BMMMMMM*****MMMMMM**********RRRRRRRRRRRRRR***EEEEEEEEEEEEE****GGGGGGGGGGGGGG***GIII*****OOOOOOOOOOOOO****NNNNN*****NNNN****SSSSSSSSSSSS***
//*SSSSSSSSSSSSS***SSSSSSSSSSSSS****BBBBBBBBBBBBBB**BMMMMMM****MMMMMMM**********RRRRRRRRRRRRRR***EEEEEEEEEEEEE***GGGGGGGGGGGGGGG***GIII****OOOOOOOOOOOOOO****NNNNNN****NNNN***SSSSSSSSSSSSS***
//*SSSSS****SSSSS**SSSSS****SSSSS***BBBB*****BBBBB**BMMMMMMM***MMMMMMM**********RRRR*****RRRRR***EEEE************GGGGG*****GGGGGG**GIII***OOOOOO****OOOOOO***NNNNNNN***NNNN***SSSS*****SSSS***
//*SSSSS****SSSSS**SSSSS****SSSSS***BBBB******BBBB**BMMMMMMM***MMMMMMM**********RRRR******RRRR***EEEE***********EGGGG*******GGG****GIII***OOOOO******OOOOO***NNNNNNN***NNNN***SSSSS****SSSS***
//*SSSSSSSS********SSSSSSSS*********BBBB*****BBBBB**BMMMMMMM**MMMMMMMM**********RRRR*****RRRRR***EEEE***********EGGGG**************GIII***OOOO********OOOOO**NNNNNNNN**NNNN***SSSSSSSS********
//**SSSSSSSSSS******SSSSSSSSSS******BBBBBBBBBBBBB***BMMMMMMMM*MMMMMMMM**********RRRRRRRRRRRRRR***EEEEEEEEEEEEE**EGGG***************GIII**IOOOO********OOOOO**NNNNNNNN**NNNN***SSSSSSSSSSS*****
//**SSSSSSSSSSSS****SSSSSSSSSSSS****BBBBBBBBBBBB****BMMMMMMMM*MMM*MMMM**********RRRRRRRRRRRRR****EEEEEEEEEEEEE**EGGG****GGGGGGGGG**GIII**IOOOO********OOOOO**NNNNNNNNN*NNNN****SSSSSSSSSSSS***
//****SSSSSSSSSSS*****SSSSSSSSSSS***BBBBBBBBBBBBB***BMMMMMMMM*MMM*MMMM**********RRRRRRRRRRRR*****EEEEEEEEEEEEE**EGGG****GGGGGGGGG**GIII**IOOOO********OOOOO**NNNN*NNNNNNNNN******SSSSSSSSSS***
//*******SSSSSSSS********SSSSSSSS***BBBBBBBBBBBBBB**BMMMM*MMMMMMM*MMMM**********RRRRRRRRRRR******EEEEEEEEEEEEE**EGGG****GGGGGGGGG**GIII**IOOOO********OOOOO**NNNN*NNNNNNNNN*********SSSSSSSS**
//*SSSS*****SSSSS**SSSS*****SSSSS***BBBB******BBBBB*BMMMM*MMMMMMM*MMMM**********RRRR**RRRRRR*****EEEE***********EGGGG***GGGGGGGGG**GIII***OOOO********OOOOO**NNNN**NNNNNNNN**NSSS******SSSSS**
//*SSSS******SSSS**SSSS******SSSS***BBBB******BBBBB*BMMMM*MMMMMMM*MMMM**********RRRR***RRRRRR****EEEE***********EGGGG********GGGG**GIII***OOOOO******OOOOO***NNNN**NNNNNNNN**NSSSS******SSSS**
//*SSSSS****SSSSS**SSSSS****SSSSS***BBBB******BBBBB*BMMMM*MMMMMM**MMMM**********RRRR****RRRRR****EEEE************GGGGG*****GGGGGG**GIII***OOOOOO****OOOOOO***NNNN***NNNNNNN***SSSSS****SSSSS**
//*SSSSSSSSSSSSSS**SSSSSSSSSSSSSS***BBBBBBBBBBBBBB**BMMMM**MMMMM**MMMM**********RRRR****RRRRRR***EEEEEEEEEEEEE***GGGGGGGGGGGGGGGG**GIII****OOOOOOOOOOOOOO****NNNN****NNNNNN***SSSSSSSSSSSSSS**
//**SSSSSSSSSSSS****SSSSSSSSSSSS****BBBBBBBBBBBBBB**BMMMM**MMMMM**MMMM**********RRRR*****RRRRR***EEEEEEEEEEEEE****GGGGGGGGGGGGGG***GIII*****OOOOOOOOOOOOO****NNNN****NNNNNN****SSSSSSSSSSSS***
//***SSSSSSSSSS******SSSSSSSSSS*****BBBBBBBBBBBBB***BMMMM**MMMMM**MMMM**********RRRR******RRRRR**EEEEEEEEEEEEE*****GGGGGGGGGGGG****GIII******OOOOOOOOOO******NNNN*****NNNNN*****SSSSSSSSSS****
//*****SSSSSS**********SSSSSS*******BBBBBBBBBBBB****BMMMM**MMMM***MMMM**********RRRR******RRRRR**EEEEEEEEEEEEE********GGGGGG*******GIII********OOOOOO********NNNN*****NNNNN******SSSSSSS******
//*******************************************************************************************************************************************************************************************/
//SSBM Regions Go Here!

//Options out of Wait
//Options out of Shield
//Options out of Dash
//Options out of Run
//Options out of RunBrake
//Options out of TurnBrake
//Options out of TurnRun
//Options out of Fall
//Options out of Tumble
//Options out of HitStun
//Options out of HitLag
//Options out of CliffWait
//Options out of WallTech
//Options out of Teeter
//Options out of SmashTurn
//Throw Options
//Buffered Options
//ICs Desyncs
//Rectangles

const regionArray = [
    {
        name: `Jab during Wait`,
        color: [255, 255, 255, 255],
        quadrants: [false, true, true, false],
        displayMode: 0,
        minX: 23,
        minY: 0,
        maxX: 63,
        maxY: 52,
        angleMin: 0,
        angleMax: 50,
        magnitudeMin: 0,
        magnitudeMax: 80
    },
    {
        name: `U-Tilt during Wait`,
        color: [255, 255, 255, 255],
        quadrants: [true, true, false, false],
        displayMode: 0,
        minX: 0,
        minY: 23,
        maxX: 80,
        maxY: 52,
        angleMin: 50,
        angleMax: 90,
        magnitudeMin: 0,
        magnitudeMax: 80
    },
    {
        name: `F-Tilt (Upper Angle, No Upper Middle Angle) during Wait`,
        color: [255, 255, 255, 255],
        quadrants: [true, false, false, false],
        displayMode: 0,
        minX: 23,
        minY: 23,
        maxX: 63,
        maxY: 52,
        angleMin: 0,
        angleMax: 50,
        magnitudeMin: 0,
        magnitudeMax: 80
    },
    {
        name: `F-Tilt (No Angled F-Tilts) during Wait`,
        color: [255, 255, 255, 255],
        quadrants: [true, false, false, true],
        displayMode: 0,
        minX: 23,
        minY: 0,
        maxX: 63,
        maxY: 52,
        angleMin: 0,
        angleMax: 90,
        magnitudeMin: 0,
        magnitudeMax: 80
    },
    {
        name: `F-Tilt (Middle Angle, Yes Angled F-Tilts) during Wait`,
        color: [255, 255, 255, 255],
        quadrants: [true, false, false, true],
        displayMode: 0,
        minX: 23,
        minY: 0,
        maxX: 63,
        maxY: 22,
        angleMin: 0,
        angleMax: 90,
        magnitudeMin: 0,
        magnitudeMax: 80
    },
    {
        name: `F-Tilt (Downward Angle, No Downward Middle Angle) during Wait`,
        color: [255, 255, 255, 255],
        quadrants: [false, false, false, true],
        displayMode: 0,
        minX: 23,
        minY: 23,
        maxX: 63,
        maxY: 52,
        angleMin: 0,
        angleMax: 50,
        magnitudeMin: 0,
        magnitudeMax: 80
    },
    {
        name: `D-Tilt during Wait`,
        color: [255, 255, 255, 255],
        quadrants: [false, false, true, true],
        displayMode: 0,
        minX: 0,
        minY: 23,
        maxX: 80,
        maxY: 52,
        angleMin: 0,
        angleMax: 50,
        magnitudeMin: 0,
        magnitudeMax: 80
    },
    {
        name: `U-Smash during Wait`,
        color: [255, 255, 255, 255],
        quadrants: [true, true, false, false],
        displayMode: 0,
        minX: 0,
        minY: 53,
        maxX: 80,
        maxY: 80,
        angleMin: 0,
        angleMax: 90,
        magnitudeMin: 0,
        magnitudeMax: 80
    },
    {
        name: `F-Smash (Upper Angle, No Upper Middle Angle) during Wait`,
        color: [255, 255, 255, 255],
        quadrants: [true, true, false, false],
        displayMode: 0,
        minX: 64,
        minY: 23,
        maxX: 76,
        maxY: 80,
        angleMin: 16.84,
        angleMax: 37,
        magnitudeMin: 0,
        magnitudeMax: 80
    },
    {
        name: `F-Smash (Upper Angle, Yes Upper Middle Angle) during Wait`,
        color: [255, 255, 255, 255],
        quadrants: [true, true, false, false],
        displayMode: 0,
        minX: 64,
        minY: 24,
        maxX: 76,
        maxY: 80,
        angleMin: 16.85,
        angleMax: 37,
        magnitudeMin: 0,
        magnitudeMax: 80
    },
    {
        name: `F-Smash (Upper Middle Angle) during Wait`,
        color: [255, 255, 255, 255],
        quadrants: [true, true, false, false],
        displayMode: 0,
        minX: 76,
        minY: 23,
        maxX: 76,
        maxY: 23,
        angleMin: 16.84,
        angleMax: 16.84,
        magnitudeMin: 0,
        magnitudeMax: 80
    },
    {
        name: `F-Smash (No Angled F-Smashs) during Wait`,
        color: [255, 255, 255, 255],
        quadrants: [true, true, true, true],
        displayMode: 0,
        minX: 64,
        minY: 0,
        maxX: 80,
        maxY: 80,
        angleMin: 0,
        angleMax: 90,
        magnitudeMin: 0,
        magnitudeMax: 80
    },
    {
        name: `F-Smash (Middle Angle, Yes Angled F-Smashs) during Wait`,
        color: [255, 255, 255, 255],
        quadrants: [true, true, true, true],
        displayMode: 0,
        minX: 64,
        minY: 0,
        maxX: 80,
        maxY: 22,
        angleMin: 0,
        angleMax: 90,
        magnitudeMin: 0,
        magnitudeMax: 80
    },
    {
        name: `F-Smash (Downward Middle Angle) during Wait`,
        color: [255, 255, 255, 255],
        quadrants: [false, false, true, true],
        displayMode: 0,
        minX: 76,
        minY: 23,
        maxX: 76,
        maxY: 23,
        angleMin: 16.84,
        angleMax: 16.84,
        magnitudeMin: 0,
        magnitudeMax: 80
    },
    {
        name: `F-Smash (Downward Angle, Yes Downward Middle Angle) during Wait`,
        color: [255, 255, 255, 255],
        quadrants: [false, false, true, true],
        displayMode: 0,
        minX: 64,
        minY: 24,
        maxX: 76,
        maxY: 80,
        angleMin: 16.85,
        angleMax: 37,
        magnitudeMin: 0,
        magnitudeMax: 80
    },
    {
        name: `F-Smash (Downward Angle, No Downward Middle Angle) during Wait`,
        color: [255, 255, 255, 255],
        quadrants: [false, false, true, true],
        displayMode: 0,
        minX: 64,
        minY: 23,
        maxX: 76,
        maxY: 80,
        angleMin: 16.84,
        angleMax: 37,
        magnitudeMin: 0,
        magnitudeMax: 80
    },
    {
        name: `D-Smash during Wait`,
        color: [255, 255, 255, 255],
        quadrants: [false, false, true, true],
        displayMode: 0,
        minX: 0,
        minY: 53,
        maxX: 80,
        maxY: 80,
        angleMin: 0,
        angleMax: 90,
        magnitudeMin: 0,
        magnitudeMax: 80
    },
    {
        name: `N-Air`,
        color: [255, 255, 255, 255],
        quadrants: [true, true, true, true],
        displayMode: 0,
        minX: 0,
        minY: 0,
        maxX: 22,
        maxY: 22,
        angleMin: 0,
        angleMax: 90,
        magnitudeMin: 0,
        magnitudeMax: 80
    },
    {
        name: `U-Air`,
        color: [255, 255, 255, 255],
        quadrants: [true, true, false, false],
        displayMode: 0,
        minX: 0,
        minY: 23,
        maxX: 80,
        maxY: 80,
        angleMin: 50,
        angleMax: 90,
        magnitudeMin: 0,
        magnitudeMax: 80
    },
    {
        name: `F-Air`,
        color: [255, 255, 255, 255],
        quadrants: [true, false, false, true],
        displayMode: 0,
        minX: 23,
        minY: 0,
        maxX: 80,
        maxY: 80,
        angleMin: 0,
        angleMax: 50,
        magnitudeMin: 0,
        magnitudeMax: 80
    },
    {
        name: `D-Air`,
        color: [255, 255, 255, 255],
        quadrants: [false, false, true, true],
        displayMode: 0,
        minX: 0,
        minY: 23,
        maxX: 80,
        maxY: 80,
        angleMin: 50,
        angleMax: 90,
        magnitudeMin: 0,
        magnitudeMax: 80
    },
    {
        name: `B-Air`,
        color: [255, 255, 255, 255],
        quadrants: [false, true, true, false],
        displayMode: 0,
        minX: 23,
        minY: 0,
        maxX: 80,
        maxY: 80,
        angleMin: 0,
        angleMax: 50,
        magnitudeMin: 0,
        magnitudeMax: 80
    },
    {
        name: `N-Special (Ground) during Wait`,
        color: [255, 255, 255, 255],
        quadrants: [true, true, true, true],
        displayMode: 0,
        minX: 0,
        minY: 0,
        maxX: 47,
        maxY: 43,
        angleMin: 0,
        angleMax: 90,
        magnitudeMin: 0,
        magnitudeMax: 80
    },
    {
        name: `U-Special (Ground) during Wait`,
        color: [255, 255, 255, 255],
        quadrants: [true, true, false, false],
        displayMode: 0,
        minX: 0,
        minY: 44,
        maxX: 44,
        maxY: 80,
        angleMin: 0,
        angleMax: 90,
        magnitudeMin: 0,
        magnitudeMax: 80
    },
    {
        name: `F-Special (Ground) during Wait`,
        color: [255, 255, 255, 255],
        quadrants: [true, true, true, true],
        displayMode: 0,
        minX: 48,
        minY: 80,
        maxX: 80,
        maxY: 80,
        angleMin: 0,
        angleMax: 90,
        magnitudeMin: 0,
        magnitudeMax: 80
    },
    {
        name: `D-Special (Ground) during Wait`,
        color: [255, 255, 255, 255],
        quadrants: [false, false, true, true],
        displayMode: 0,
        minX: 0,
        minY: 45,
        maxX: 47,
        maxY: 80,
        angleMin: 0,
        angleMax: 90,
        magnitudeMin: 0,
        magnitudeMax: 80
    },
    {
        name: `Specials Disabled during Wait`,
        color: [255, 255, 255, 255],
        quadrants: [false, false, true, true],
        displayMode: 0,
        minX: 0,
        minY: 44,
        maxX: 47,
        maxY: 44,
        angleMin: 0,
        angleMax: 90,
        magnitudeMin: 0,
        magnitudeMax: 80
    },
    {
        name: `N-Special (Air)`,
        color: [255, 255, 255, 255],
        quadrants: [true, true, true, true],
        displayMode: 0,
        minX: 0,
        minY: 0,
        maxX: 22,
        maxY: 43,
        angleMin: 0,
        angleMax: 90,
        magnitudeMin: 0,
        magnitudeMax: 80
    },
    {
        name: `Turnaround N-Special`,
        color: [255, 255, 255, 255],
        quadrants: [true, true, true, true],
        displayMode: 0,
        minX: 23,
        minY: 0,
        maxX: 47,
        maxY: 43,
        angleMin: 0,
        angleMax: 90,
        magnitudeMin: 0,
        magnitudeMax: 80
    },
    {
        name: `U-Special (Air)`,
        color: [255, 255, 255, 255],
        quadrants: [true, true, false, false],
        displayMode: 0,
        minX: 0,
        minY: 44,
        maxX: 80,
        maxY: 80,
        angleMin: 0,
        angleMax: 90,
        magnitudeMin: 0,
        magnitudeMax: 80
    },
    {
        name: `F-Special (Air)`,
        color: [255, 255, 255, 255],
        quadrants: [true, true, true, true],
        displayMode: 0,
        minX: 48,
        minY: 0,
        maxX: 80,
        maxY: 43,
        angleMin: 0,
        angleMax: 90,
        magnitudeMin: 0,
        magnitudeMax: 80
    },
    {
        name: `D-Special (Air)`,
        color: [255, 255, 255, 255],
        quadrants: [false, false, true, true],
        displayMode: 0,
        minX: 0,
        minY: 44,
        maxX: 80,
        maxY: 80,
        angleMin: 0,
        angleMax: 90,
        magnitudeMin: 0,
        magnitudeMax: 80
    },
    {
        name: `U-Throw`,
        color: [255, 255, 255, 255],
        quadrants: [true, true, false, false],
        displayMode: 0,
        minX: 0,
        minY: 0,
        maxX: 22,
        maxY: 80,
        angleMin: 0,
        angleMax: 90,
        magnitudeMin: 0,
        magnitudeMax: 80
    },
    {
        name: `F-Throw`,
        color: [255, 255, 255, 255],
        quadrants: [true, false, false, true],
        displayMode: 0,
        minX: 23,
        minY: 0,
        maxX: 80,
        maxY: 80,
        angleMin: 0,
        angleMax: 90,
        magnitudeMin: 0,
        magnitudeMax: 80
    },
    {
        name: `D-Throw`,
        color: [255, 255, 255, 255],
        quadrants: [false, false, true, true],
        displayMode: 0,
        minX: 0,
        minY: 0,
        maxX: 22,
        maxY: 80,
        angleMin: 0,
        angleMax: 90,
        magnitudeMin: 0,
        magnitudeMax: 80
    },
    {
        name: `B-Throw`,
        color: [255, 255, 255, 255],
        quadrants: [false, true, true, false],
        displayMode: 0,
        minX: 23,
        minY: 0,
        maxX: 80,
        maxY: 80,
        angleMin: 0,
        angleMax: 90,
        magnitudeMin: 0,
        magnitudeMax: 80
    },
    {
        name: `Shield Tilt during Shield (Grounded Only) (1/2)`,
        color: [255, 255, 255, 255],
        quadrants: [true, true, false, false],
        displayMode: 0,
        minX: 0,
        minY: 0,
        maxX: 55,
        maxY: 52,
        angleMin: 0,
        angleMax: 90,
        magnitudeMin: 0,
        magnitudeMax: 80
    },
    {
        name: `Shield Tilt during Shield (Grounded Only) (2/2)`,
        color: [255, 255, 255, 255],
        quadrants: [false, false, true, true],
        displayMode: 0,
        minX: 0,
        minY: 0,
        maxX: 55,
        maxY: 55,
        angleMin: 0,
        angleMax: 90,
        magnitudeMin: 0,
        magnitudeMax: 80
    },
    {
        name: `Tap Jump during Shield (Grounded Only) (1/2)`,
        color: [255, 255, 255, 255],
        quadrants: [true, true, false, false],
        displayMode: 0,
        minX: 0,
        minY: 56,
        maxX: 55,
        maxY: 80,
        angleMin: 0,
        angleMax: 90,
        magnitudeMin: 0,
        magnitudeMax: 80
    },
    {
        name: `Tap Jump during Shield (Grounded Only) (2/2)`,
        color: [255, 255, 255, 255],
        quadrants: [true, true, false, false],
        displayMode: 0,
        minX: 0,
        minY: 0,
        maxX: 55,
        maxY: 52,
        angleMin: 0,
        angleMax: 90,
        magnitudeMin: 0,
        magnitudeMax: 80
    },
    {
        name: `Roll during Shield (Grounded Only)`,
        color: [255, 255, 255, 255],
        quadrants: [true, true, true, true],
        displayMode: 0,
        minX: 56,
        minY: 0,
        maxX: 80,
        maxY: 57,
        angleMin: 0,
        angleMax: 90,
        magnitudeMin: 0,
        magnitudeMax: 80
    },
    {
        name: `Spotdodge during Shield (Grounded Only)`,
        color: [255, 255, 255, 255],
        quadrants: [false, false, true, true],
        displayMode: 0,
        minX: 0,
        minY: 56,
        maxX: 55,
        maxY: 80,
        angleMin: 0,
        angleMax: 90,
        magnitudeMin: 0,
        magnitudeMax: 80
    },
    {
        name: `Shield Tilt during Shield (Platform Only)`,
        color: [255, 255, 255, 255],
        quadrants: [true, true, true, true],
        displayMode: 0,
        minX: 0,
        minY: 55,
        maxX: 0,
        maxY: 52,
        angleMin: 0,
        angleMax: 90,
        magnitudeMin: 0,
        magnitudeMax: 80
    },
    {
        name: `Tap Jump during Shield (Platform Only) (1/2)`,
        color: [255, 255, 255, 255],
        quadrants: [true, true, false, false],
        displayMode: 0,
        minX: 0,
        minY: 56,
        maxX: 55,
        maxY: 80,
        angleMin: 0,
        angleMax: 90,
        magnitudeMin: 0,
        magnitudeMax: 80
    },
    {
        name: `Tap Jump during Shield (Platform Only) (2/2)`,
        color: [255, 255, 255, 255],
        quadrants: [true, true, false, false],
        displayMode: 0,
        minX: 0,
        minY: 53,
        maxX: 55,
        maxY: 55,
        angleMin: 0,
        angleMax: 90,
        magnitudeMin: 0,
        magnitudeMax: 80
    },
    {
        name: `Roll during Shield (Platform Only)`,
        color: [255, 255, 255, 255],
        quadrants: [true, true, true, true],
        displayMode: 0,
        minX: 56,
        minY: 80,
        maxX: 0,
        maxY: 57,
        angleMin: 0,
        angleMax: 90,
        magnitudeMin: 0,
        magnitudeMax: 80
    },
    {
        name: `Spotdodge during Shield (Platform Only)`,
        color: [255, 255, 255, 255],
        quadrants: [false, false, true, true],
        displayMode: 0,
        minX: 0,
        minY: 56,
        maxX: 55,
        maxY: 80,
        angleMin: 0,
        angleMax: 90,
        magnitudeMin: 0,
        magnitudeMax: 80
    },
    {
        name: `Shield Drop during Shield (Platform Only)`,
        color: [255, 255, 255, 255],
        quadrants: [false, false, true, true],
        displayMode: 0,
        minX: 0,
        minY: 0,
        maxX: 55,
        maxY: 52,
        angleMin: 0,
        angleMax: 90,
        magnitudeMin: 0,
        magnitudeMax: 80
    },




    {
        name: `Dash during Wait (1/2)`,
        color: [255, 255, 255, 255],
        quadrants: [true, false, false, true],
        displayMode: 0,
        minX: 64,
        minY: 0,
        maxX: 80,
        maxY: 44,
        angleMin: 0,
        angleMax: 90,
        magnitudeMin: 0,
        magnitudeMax: 80
    },
    {
        name: `Dash during Wait (2/2)`,
        color: [255, 255, 255, 255],
        quadrants: [false, false, false, true],
        displayMode: 0,
        minX: 64,
        minY: 45,
        maxX: 66,
        maxY: 48,
        angleMin: 0,
        angleMax: 90,
        magnitudeMin: 0,
        magnitudeMax: 80
    },
    {
        name: `Walk (Slow) during Wait (Grounded Only) (1/2)`,
        color: [255, 255, 255, 255],
        quadrants: [true, false, false, false],
        displayMode: 0,
        minX: 23,
        minY: 0,
        maxX: 33,
        maxY: 52,
        angleMin: 0,
        angleMax: 90,
        magnitudeMin: 0,
        magnitudeMax: 80
    },
    {
        name: `Walk (Slow) during Wait (Grounded Only) (2/2)`,
        color: [255, 255, 255, 255],
        quadrants: [false, false, false, true],
        displayMode: 0,
        minX: 23,
        minY: 0,
        maxX: 33,
        maxY: 49,
        angleMin: 0,
        angleMax: 90,
        magnitudeMin: 0,
        magnitudeMax: 80
    },
    {
        name: `Walk (Mid) during Wait (Grounded Only) (1/2)`,
        color: [255, 255, 255, 255],
        quadrants: [true, false, false, false],
        displayMode: 0,
        minX: 34,
        minY: 0,
        maxX: 58,
        maxY: 52,
        angleMin: 0,
        angleMax: 90,
        magnitudeMin: 0,
        magnitudeMax: 80
    },
    {
        name: `Walk (Mid) during Wait (Grounded Only) (2/2)`,
        color: [255, 255, 255, 255],
        quadrants: [false, false, false, true],
        displayMode: 0,
        minX: 34,
        minY: 0,
        maxX: 58,
        maxY: 49,
        angleMin: 0,
        angleMax: 90,
        magnitudeMin: 0,
        magnitudeMax: 80
    },
    {
        name: `Walk (Fast) during Wait (Grounded Only) (1/2)`,
        color: [255, 255, 255, 255],
        quadrants: [true, false, false, false],
        displayMode: 0,
        minX: 59,
        minY: 0,
        maxX: 63,
        maxY: 52,
        angleMin: 0,
        angleMax: 90,
        magnitudeMin: 0,
        magnitudeMax: 80
    },
    {
        name: `Walk (Fast) during Wait (Grounded Only) (2/2)`,
        color: [255, 255, 255, 255],
        quadrants: [false, false, false, true],
        displayMode: 0,
        minX: 59,
        minY: 0,
        maxX: 63,
        maxY: 49,
        angleMin: 0,
        angleMax: 90,
        magnitudeMin: 0,
        magnitudeMax: 80
    },
    {
        name: `Tilt Turn during Wait (Grounded Only) (1/2)`,
        color: [255, 255, 255, 255],
        quadrants: [false, true, false, false],
        displayMode: 0,
        minX: 23,
        minY: 63,
        maxX: 0,
        maxY: 52,
        angleMin: 0,
        angleMax: 90,
        magnitudeMin: 0,
        magnitudeMax: 80
    },
    {
        name: `Tilt Turn during Wait (Grounded Only) (2/2)`,
        color: [255, 255, 255, 255],
        quadrants: [false, false, true, false],
        displayMode: 0,
        minX: 23,
        minY: 63,
        maxX: 0,
        maxY: 49,
        angleMin: 0,
        angleMax: 90,
        magnitudeMin: 0,
        magnitudeMax: 80
    },
    {
        name: `Smash Turn during Wait (Grounded Only)`,
        color: [255, 255, 255, 255],
        quadrants: [false, true, true, false],
        displayMode: 0,
        minX: 64,
        minY: 0,
        maxX: 80,
        maxY: 48,
        angleMin: 0,
        angleMax: 90,
        magnitudeMin: 0,
        magnitudeMax: 80
    },
    {
        name: `Tap Jump during Wait`,
        color: [255, 255, 255, 255],
        quadrants: [true, true, false, false],
        displayMode: 0,
        minX: 0,
        minY: 80,
        maxX: 53,
        maxY: 80,
        angleMin: 0,
        angleMax: 90,
        magnitudeMin: 0,
        magnitudeMax: 80
    },
    {
        name: `Activate Crouch (Squat) during Wait (Grounded Only) (1/2)`,
        color: [255, 255, 255, 255],
        quadrants: [false, false, true, true],
        displayMode: 0,
        minX: 0,
        minY: 56,
        maxX: 80,
        maxY: 80,
        angleMin: 0,
        angleMax: 90,
        magnitudeMin: 0,
        magnitudeMax: 80
    },
    {
        name: `Activate Crouch (Squat) during Wait (Grounded Only) (2/2)`,
        color: [255, 255, 255, 255],
        quadrants: [false, false, true, true],
        displayMode: 0,
        minX: 23,
        minY: 50,
        maxX: 62,
        maxY: 55,
        angleMin: 0,
        angleMax: 90,
        magnitudeMin: 0,
        magnitudeMax: 80
    },


    {
        name: `Tap Jump during Dash`,
        color: [255, 255, 255, 255],
        quadrants: [true, true, false, false],
        displayMode: 0,
        minX: 0,
        minY: 45,
        maxX: 66,
        maxY: 80,
        angleMin: 0,
        angleMax: 90,
        magnitudeMin: 0,
        magnitudeMax: 80
    },


    {
        name: `Ledgejump during CliffWait`,
        color: [255, 255, 255, 255],
        quadrants: [true, true, false, false],
        displayMode: 0,
        minX: 0,
        minY: 53,
        maxX: 59,
        maxY: 80,
        angleMin: 0,
        angleMax: 90,
        magnitudeMin: 0,
        magnitudeMax: 80
    },
    {
        name: `Climb Up during CliffWait (1/3)`,
        color: [255, 255, 255, 255],
        quadrants: [true, true, false, false],
        displayMode: 0,
        minX: 0,
        minY: 23,
        maxX: 80,
        maxY: 52,
        angleMin: 50,
        angleMax: 90,
        magnitudeMin: 0,
        magnitudeMax: 80
    },
    {
        name: `Climb Up during CliffWait (2/3)`,
        color: [255, 255, 255, 255],
        quadrants: [true, false, false, false],
        displayMode: 0,
        minX: 23,
        minY: 0,
        maxX: 80,
        maxY: 52,
        angleMin: 0,
        angleMax: 50,
        magnitudeMin: 0,
        magnitudeMax: 80
    },
    {
        name: `Climb Up during CliffWait (3/3)`,
        color: [255, 255, 255, 255],
        quadrants: [false, false, false, true],
        displayMode: 0,
        minX: 23,
        minY: 0,
        maxX: 80,
        maxY: 60,
        angleMin: 0,
        angleMax: 50,
        magnitudeMin: 0,
        magnitudeMax: 80
    },
    {
        name: `Ledgedrop and Fast Fall afterwards during CliffWait (1/2)`,
        color: [255, 255, 255, 255],
        quadrants: [false, false, false, true],
        displayMode: 0,
        minX: 0,
        minY: 53,
        maxX: 63,
        maxY: 80,
        angleMin: 50,
        angleMax: 90,
        magnitudeMin: 0,
        magnitudeMax: 80
    },
    {
        name: `Ledgedrop and Fast Fall afterwards during CliffWait (2/2)`,
        color: [255, 255, 255, 255],
        quadrants: [false, false, true, false],
        displayMode: 0,
        minX: 0,
        minY: 53,
        maxX: 80,
        maxY: 80,
        angleMin: 0,
        angleMax: 90,
        magnitudeMin: 0,
        magnitudeMax: 80
    },
    {
        name: `Ledgedrop during CliffWait (1/2)`,
        color: [255, 255, 255, 255],
        quadrants: [false, false, true, true],
        displayMode: 0,
        minX: 0,
        minY: 23,
        maxX: 43,
        maxY: 52,
        angleMin: 50,
        angleMax: 90,
        magnitudeMin: 0,
        magnitudeMax: 80
    },
    {
        name: `Ledgedrop during CliffWait (2/2)`,
        color: [255, 255, 255, 255],
        quadrants: [false, true, true, false],
        displayMode: 0,
        minX: 23,
        minY: 0,
        maxX: 80,
        maxY: 52,
        angleMin: 0,
        angleMax: 50,
        magnitudeMin: 0,
        magnitudeMax: 80
    },


















    {
        name: `Popo F-Smash/Nana F-Tilt during Wait (Desync)`,
        color: [255, 255, 255, 255],
        quadrants: [true, true, true, true],
        displayMode: 0,
        minX: 64,
        minY: 0,
        maxX: 64,
        maxY: 80,
        angleMin: 0,
        angleMax: 90,
        magnitudeMin: 0,
        magnitudeMax: 80
    },
    {
        name: `Popo U-Smash/Nana U-Tilt during Wait (Desync)`,
        color: [255, 255, 255, 255],
        quadrants: [true, true, false, false],
        displayMode: 0,
        minX: 0,
        minY: 53,
        maxX: 80,
        maxY: 53,
        angleMin: 0,
        angleMax: 90,
        magnitudeMin: 0,
        magnitudeMax: 80
    },
    {
        name: `Popo D-Smash/Nana D-Tilt during Wait (Desync)`,
        color: [255, 255, 255, 255],
        quadrants: [false, false, true, true],
        displayMode: 0,
        minX: 0,
        minY: 53,
        maxX: 80,
        maxY: 53,
        angleMin: 0,
        angleMax: 90,
        magnitudeMin: 0,
        magnitudeMax: 80
    },
    {
        name: `Popo F-Smash during Wait (Desync)`,
        color: [255, 255, 255, 255],
        quadrants: [true, true, true, true],
        displayMode: 0,
        minX: 64,
        minY: 0,
        maxX: 64,
        maxY: 80,
        angleMin: 0,
        angleMax: 90,
        magnitudeMin: 0,
        magnitudeMax: 80
    },
    {
        name: `Popo U-Smash during Wait (Desync)`,
        color: [255, 255, 255, 255],
        quadrants: [true, true, false, false],
        displayMode: 0,
        minX: 0,
        minY: 53,
        maxX: 80,
        maxY: 53,
        angleMin: 0,
        angleMax: 90,
        magnitudeMin: 0,
        magnitudeMax: 80
    },
    {
        name: `Popo D-Smash during Wait (Desync)`,
        color: [255, 255, 255, 255],
        quadrants: [false, false, true, true],
        displayMode: 0,
        minX: 0,
        minY: 53,
        maxX: 80,
        maxY: 53,
        angleMin: 0,
        angleMax: 90,
        magnitudeMin: 0,
        magnitudeMax: 80
    },
    {
        name: `Popo Roll during Shield (Desync)`,
        color: [255, 255, 255, 255],
        quadrants: [true, true, true, true],
        displayMode: 0,
        minX: 56,
        minY: 0,
        maxX: 56,
        maxY: 80,
        angleMin: 0,
        angleMax: 90,
        magnitudeMin: 0,
        magnitudeMax: 80
    },
    {
        name: `Popo Spotdodge/Nana Shield Drop during Shield (Platform Only) (Desync)`,
        color: [255, 255, 255, 255],
        quadrants: [false, false, true, true],
        displayMode: 0,
        minX: 0,
        minY: 56,
        maxX: 80,
        maxY: 56,
        angleMin: 0,
        angleMax: 90,
        magnitudeMin: 0,
        magnitudeMax: 80
    },
    {
        name: `Popo Spotdodge/Nana Shield Drop during Shield (Platform Only) (Desync), UCF v0.73, UCF v0.80`,
        color: [255, 255, 255, 255],
        quadrants: [false, false, true, true],
        displayMode: 0,
        minX: 0,
        minY: 64,
        maxX: 80,
        maxY: 64,
        angleMin: 0,
        angleMax: 90,
        magnitudeMin: 0,
        magnitudeMax: 80
    },
    {
        name: `Popo Run/Nana Runbrake (Desync)`,
        color: [255, 255, 255, 255],
        quadrants: [true, false, false, true],
        displayMode: 0,
        minX: 50,
        minY: 0,
        maxX: 50,
        maxY: 80,
        angleMin: 0,
        angleMax: 90,
        magnitudeMin: 0,
        magnitudeMax: 80
    },
    {
        name: `Popo Teeter Break/Nana Teeter (Desync)`,
        color: [255, 255, 255, 255],
        quadrants: [true, false, false, true],
        displayMode: 0,
        minX: 60,
        minY: 0,
        maxX: 60,
        maxY: 80,
        angleMin: 0,
        angleMax: 90,
        magnitudeMin: 0,
        magnitudeMax: 80
    },
    {
        name: `Popo Jump out of Dash/Run/Runbrake/Turnrun (Desync)`,
        color: [255, 255, 255, 255],
        quadrants: [true, true, false, false],
        displayMode: 0,
        minX: 0,
        minY: 45,
        maxX: 80,
        maxY: 45,
        angleMin: 0,
        angleMax: 80,
        magnitudeMin: 0,
        magnitudeMax: 80
    },
    {
        name: `Nana Grounded N-Special (Grounded Only) (Desync)`,
        color: [255, 255, 255, 255],
        quadrants: [false, false, true, true],
        displayMode: 0,
        minX: 0,
        minY: 44,
        maxX: 47,
        maxY: 44,
        angleMin: 0,
        angleMax: 90,
        magnitudeMin: 0,
        magnitudeMax: 80
    }
]
